detectors = [
    "detect-secrets",
    "git-secrets",
#    "trufflehog"
]

[auth]
access_token='env'

[monitors]
    organizations = ['brightcove', 'BrightcoveOS', 'BrightcovePS', 'zencoder']
    users = []
    repos = []

[webhook]
    secret=""
    host="0.0.0.0"

[notifiers.console]

[notifiers.slack_webhook]
    webhook_url='env'
